#!/usr/bin/env python3
# Generated by the SARL compiler the Thu Oct 13 19:57:43 CEST 2022. Do not change this file.

#### GENERATED PYTHON CODE

# class LoggingSkill(object):
# 	def info(self, text : unicode) -> :
# 		print(text)
# 	def debug(self, text_1 : unicode) -> :
# 		print(text)
# 	def __init__(self):
# 		pass


#### GENERATES PYTHON CODE WITH NECESSARY MODIFICATION
from vm.LoggingAgent.Logging import Logging
from pysarl.io.sarl.lang.core.Skill import Skill

class LoggingSkill(Skill, Logging, object):
    def info(self, text):
        print(text)

    def debug(self, text):
        print(text)

    def __init__(self):
        pass
