#!/usr/bin/env python3
# Generated by the SARL compiler the Sun Oct 23 23:39:11 CEST 2022. Do not change this file.

from contribs.io.sarl.pythongenerator.api.agent.agent import Agent
from contribs.io.sarl.pythongenerator.vm.builtin.capacity.Lifecycle import Lifecycle
from contribs.io.sarl.pythongenerator.vm.PingPong.PingAgent import PingAgent
from contribs.io.sarl.pythongenerator.vm.PingPong.PongAgent import PongAgent


class BootPingPongAgent(Agent, object):
    def __on_Initialize__(self, occurrence):
        self.getSkill(Lifecycle).spawn(PingAgent, occurrence)
        self.getSkill(Lifecycle).spawn(PongAgent, occurrence)
        self.getSkill(Lifecycle).killMe_1()

    def __guard_io_sarl_core_Initialize__(self, occurrence):
        it = occurrence
        __event_handles = list()
        __event_handles.append(self.__on_Initialize__)
        return __event_handles

    def __init__(self, parentID, agentID, dynamicSkillProvider = None):
        super().__init__(parentID, agentID, dynamicSkillProvider)
