#!/usr/bin/env python3
# Generated by the SARL compiler the Thu Oct 13 20:11:56 CEST 2022. Do not change this file.
from pysarl.io.sarl.lang.core.Event import Event


#class event4(object):
#	def __init__(self):
#		self.subsubid = 2

class event4(event3):
	def __init__(self,n):
		super().__init__(n)
		self.subsubid = 2