#!/usr/bin/env python3
# Generated by the SARL compiler the Thu Oct 13 19:57:44 CEST 2022. Do not change this file.


#### GENERATED PYTHON CODE OF THE FIRST VERSION OF HELLOWORLD
""""
from io.sarl.lang.core import Agent
from org.eclipse.xtext.xbase.lib import InputOutput

class BootAgent(Agent,object):
	def __on_Initialize__(self, occurrence):
		InputOutput.println(u"Hello World!")
	def __guard_io_sarl_core_Initialize__(self, occurrence):
		it = occurrence
		__event_handles = list
		__event_handles.add(__on_Initialize__)
		return __event_handles
	def __init__(self):
		pass
"""

#### GENERATED PYTHON CODE OF THE FIRST VERSION OF HELLOWORLD
"""
from io.sarl.core import Lifecycle
from io.sarl.lang.core import Agent

class BootAgent(Agent,object):
	def __on_Initialize__(self, occurrence):
		self.info(u"Hello World!")
		self.getSkill(Lifecycle).killMe()
	def __guard_io_sarl_core_Initialize__(self, occurrence):
		it = occurrence
		__event_handles = list
		__event_handles.add(__on_Initialize__)
		return __event_handles
	def __init__(self):
		pass
"""

#### PYTHON CODE WITH NECESSARY MODIFICATIONS

from pysarl.io.sarl.lang.core.Agent import Agent
from vm.builtin.capacity.Lifecycle import Lifecycle
from vm.builtin.capacity.Logging import Logging


class HelloWorldAgent(Agent, object):

    def __on_Initialize__(self, occurrence):
        self.getSkill(Logging).debug(u"Hello World!d")
        self.getSkill(Logging).info(u"Hello World!i")
        self.getSkill(Logging).warning(u"Hello World!w")
        self.getSkill(Logging).error(u"Hello World!e")
        self.getSkill(Lifecycle).killMe()

        # self.getSkill(Lifecycle).killMe()

    def __guard_io_sarl_core_Initialize__(self, occurrence):
        it = occurrence
        __event_handles = list()
        __event_handles.append(self.__on_Initialize__)
        return __event_handles

    def __on_Destroy__(self, occurrence):
        self.getSkill(Logging).debug(u"Goodbye World!d")

    def __guard_io_sarl_core_Destroy__(self, occurrence):
        it = occurrence
        __event_handles = list()
        __event_handles.append(self.__on_Destroy__)
        return __event_handles

    def __init__(self, parentID, agentID, dynamicSkillProvider=None):
        super().__init__(parentID, agentID, dynamicSkillProvider)
